
model:
  NAME: BaseSeg
  encoder_args:
    NAME: TobiasVortexBoundaryUnet
    in_channels: 2
    out_channels: 2
    DataSizeX: 16
    DataSizeY: 16
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of TobiasVortexBoundaryCNN
# ---------------------------------------------------------------------------- #
# Training parameters
# random_seed: 4259
# wandb: True 
lr: 0.001
epochs: 300
scheduler: TwoStep
warmup_epochs: 100 
second_lr: 0.0001



dataloader:
  num_workers: 0
dataset:
  NAME: SteadyVastisSegmentation
  data_dir: 'CppProjects/data/Steady/X16_Y16_Steady'

datatransforms:
  train: [ToTensor,WhiteNoise]  # rotation does not help
  val: [ToTensor,WhiteNoise]
  test: [ToTensor,WhiteNoise]
  kwargs:
    noiseMaginitude: 0.01
  

test_tasks:
      tasks: ["TestSegmentation"] 



