
model:
  NAME: BaseCls
  encoder_args:
    NAME: TobiasVortexBoundaryCNN
    in_channels: 2
    DataSizeX: 16
    DataSizeY: 16
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of TobiasVortexBoundaryCNN
# ---------------------------------------------------------------------------- #
# Training parameters

lr: 0.001
second_lr: 0.0001
epochs: 100
warmup_epochs: 80 
scheduler: TwoStep
random_seed: 4259
wandb: True 



dataloader:
  num_workers: 0
dataset:
  NAME: SteadyVastisClassification
  data_dir: 'CppProjects/data/Steady/X16_Y16_Steady'

datatransforms:
  train: [ToTensor,WhiteNoise]  # rotation does not help
  val: [ToTensor,WhiteNoise]
  test: [ToTensor,WhiteNoise]
  kwargs:
    noiseMaginitude: 0.01
  

test_tasks:
      tasks: ["TestClassification","TestRandomSamples","TestRotatingZeroField"] 



