seed: 9061
epochs: 80
train_points_count: 68000
bs: 512
print_freq: 200

lr: 0.0001
optimizer:
 NAME: 'adam'
loss:
  NAME: MSELoss

pnn:
  split: 3
  points: 1024
  stages: 1
  dim: 36
  k: 6
  alpha: 1000
  beta: 100
dataset:
  dat_dir: C:\\Users\\xingdi\\OneDrive - KAUST\\WorkingInProcess\\FLowVisAssets\\flowData2d
  name: cylinder2d #beads2d  doublegyre2d pipedcylinder2d cylinder2d
  extension: nc


# set the params to generate the point clouds
pcds:
  sample_area: full #points full areas
  line_type: p_line # streamline   p_line-> pathline
  line_method: RK4 # RK4 Euler
  dt: 0.01 # flowline integration dt 

  max_iterations: 100 # time step
  sampled_points_per_line: 4 # samples one the line
  offset_scale: 0.1 # scale of grid interval
  num_cross_points_per_seeding: 5 
  interval_scale: 2


  normalized: False
  localized: True
  
  time_slice: None # get the specific time_slice
  #params for s_lines
  t_start: 0.6 #% for the whole time
  t_target: 1.0 #


  max_seg: 50
  start_points: [[0.0,0.0]]
  bbox: [[2.5,0.5],[5.5,1.5]] # [[xmin1,ymin1] [xmax1,ymax1],[xmin2,ymin2],[xmax2,ymax2]]


cluster:
  alg: kmeans #DBSCAN kmeans
  classes: 2

  #params for DBSCAN
  eps: 5 # larger for bigger search space
  min_samples: 3 # 3-10

output:
  exp: dev







