seed: 7068
epochs: 8
train_points_count: 72000
batch_size: 24
print_freq: 200

lr: 0.0001
optimizer:
  NAME: 'adamw'
  weight_decay: 0.000001

loss:
  NAME: MSELoss

model:
  # NAME: UpsamplingUnetModel
  # NAME: FTLEUpsamplingFMT_Unet
  # NAME: FTLEUpsamplingFMT_Vit
  NAME: FTLEUpsamplingFMT_UnetV2

wandb: False 

dataset:
  timesliceCount: 10 # total data set is    NumberOfVectorFields*timesliceCount* (VectorFieldGridRes//PatchSize)   

  low_res_grid_sampling: 0.5 #low resolution ftle's grid =vectorfield.grid*low_res_grid_sampling 
  UPsampling: 4 # must be integer

  dat_dir: C:\\Users\\xingdi\\OneDrive - KAUST\\WorkingInProcess\\FLowVisAssets\\flowData2d
  # name: cylinder2d #beads2d  doublegyre2d pipedcylinder2d cylinder2d  GerrisFlowSolverData/*.am
  names: [doublegyre2d,beads2d,rfc2d]
  extension: nc
  t_start: 0.2 #% for the whole time
  t_target: 0.8
  patchSize: 32
  patchStride: 4
  
test_tasks: test_UpsamplingModel
test_vectorfield: cylinder2d




pnn:
  split: 3
  points: 1024
  stages: 0
  dim: 24
  k: 6
  alpha: 1000
  beta: 100



# set the params to generate the point clouds
pcds:
  sample_area: full #points full areas
  line_type: p_line # streamline   p_line-> pathline
  line_method: RK4 # RK4 Euler
  dt: 0.01 # flowline integration dt 

  max_iterations: 200 # time step
  sampled_points_per_line: 4 # samples one the line
  offset_dist: 0.01 # scale of grid interval
  num_cross_points_per_seeding: 5 


  normalized: False
  localized: True

  max_seg: 50
  start_points: [[0.0,0.0]]
  bbox: [[2.5,0.5],[5.5,1.5]] # [[xmin1,ymin1] [xmax1,ymax1],[xmin2,ymin2],[xmax2,ymax2]]

