
model:
  NAME: BaseCls
  encoder_args:
    NAME: LiuVortexNet
    in_channels: 2
    DataSizeX: 16
    DataSizeY: 16
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of LiuVortexNet
# ---------------------------------------------------------------------------- #
# Training parameters
batch_size: 512
lr: 0.0005
wandb: True 
dataloader:
  num_workers: 0
random_seed: 00041698924902

dataset:
  NAME: SteadyVastisDataset
  data_dir: 'CppProjects/data/Steady/X16_Y16_Steady'
 
datatransforms:
  train: [ToTensor,MinMaxNormalization] 
  val: [ToTensor,MinMaxNormalization]
  test: [ToTensor,MinMaxNormalization]
  kwargs:
    noiseMaginitude: 0.0000
  



