
model:
  NAME: BaseSeg
  encoder_args:
    NAME: DengMVUnet
    in_channels: 4
    DataSizeX: 32
    DataSizeY: 32
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of TobiasVortexBoundaryCNN
# ---------------------------------------------------------------------------- #
# Training parameters
# random_seed: 4259
# wandb: True 
lr: 0.0001
epochs: 100

scheduler: TwoStep
warmup_epochs: 100 
second_lr: 0.00001
batch_size: 64
gradient_accumulate: 1
gradient_norm_clip: 1.0

dataloader:
  num_workers: 0
dataset:
  NAME: SteadyVelocityGridSegmentationMVUnet
  # data_dir: 'CppProjects/data/Steady/X32_Y32'
  data_dir: 'CppProjects/data/IvdSegRealData/'

#add WhiteNoise will boost vortex_unet 's performance
datatransforms:
  train: [MinMaxNormalization,WhiteNoise]  # rotation does not help
  val: [MinMaxNormalization,WhiteNoise]
  test: []
  kwargs:
    noiseMaginitude: 0.02
  

test_tasks:
      tasks: ["TestSegmentation","TestVectorFieldSegmentation"] 

save_model_path: 'outputModels/'
save_model: True
save_freq: 30 # saving frequency for ckpt. -1 only saving the latest and the best.
