
model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointTransformer
    # d_model: 1152 
    num_encoder_layers: 3
    KpathlinePerGroup: 4
    PathlineGroups: 64
    in_channels: 9
    dropout: 0.5
    # DataSizeX: 32
    # DataSizeY: 32
    # TimeSteps: 5
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of TobiasVortexBoundaryCNN
# ---------------------------------------------------------------------------- #
# Training parameters
# random_seed: 4259
wandb: True 
batch_size: 68
lr: 0.0001
epochs: 120
val_freq: 5
# scheduler: TwoStep
# warmup_epochs: 80 
# second_lr: 0.00001
optimizer:
 NAME: 'adamw'
 weight_decay: 0.00001

# scheduler
scheduler: cosine
warmup_epochs:  2
warmup_lr_init: 5.0e-5
min_lr: 0.000005

save_model: true
save_freq: 30 # saving frequency for ckpt. -1 only saving the latest and the best.

# scheduler: TwoStep
# warmup_epochs: 60 
# second_lr: 0.000005

dataloader:
  num_workers: 0
dataset:
  NAME: UnsteadyVastisPathlineSeg
  data_dir: 'CppProjects/data/dbgPathline/X32_Y32_T5'

#add WhiteNoise will boost vortex_unet 's performance
datatransforms:
  train: [MinMaxNormalization,WhiteNoise]  # rotation does not help
  val: [MinMaxNormalization,WhiteNoise]
  test: []
  kwargs:
    noiseMaginitude: 0.01
  

test_tasks:
      tasks: ["TestSegmentation","TestPathlineSeg"] 



