
model:
  NAME: BaseSeg
  encoder_args:
    NAME: TobiasVortexBoundaryUnet
    in_channels: 2
    out_channels: 2
    DataSizeX: 16
    DataSizeY: 16
  criterion_args:
    NAME: BCELoss
   

# ---------------------------------------------------------------------------- #
# Training cfgs of TobiasVortexBoundaryCNN
# ---------------------------------------------------------------------------- #
# Training parameters
# random_seed: 4259
wandb: True 
lr: 0.0001
epochs: 100
scheduler: TwoStep
warmup_epochs: 80 
second_lr: 0.0001



dataloader:
  num_workers: 0
dataset:
  NAME: SteadyVastisSegmentation
  # data_dir: 'CppProjects/data/Steady/X32_Y32'
  data_dir: 'CppProjects/data/IvdSegRealData/X32_Y32'

#add WhiteNoise will boost vortex_unet 's performance
datatransforms:
  train: [WhiteNoise]  # rotation does not help
  val: [WhiteNoise]
  test: []
  kwargs:
    noiseMaginitude: 0.02
  

test_tasks:
      tasks: ["TestSegmentation","TestVectorFieldSegmentation"] 

save_model_path: 'outputModels/TobiasVortexBoundaryUnet/'
save_model: True
save_freq: 20 # saving frequency for ckpt. -1 only saving the latest and the best.
