
rendering:
  restore: False
  window_size: [1600, 1200]

network:
  input_size: 784
  hidden_layers: [128, 64]
  output_size: 10
  activation: 'relu'
  
training:
  optimizer: Adam
  learning_rate: 0.001
  epochs: 20
  loss_function: MSELoss