
network:
  family_name: 'CNN'
  hidden_size: 64
  dropout: 0.2
  # output_size: 10
  activation: 'relu'
  

dataset:
    name: 'vastis'
    root: 'C:\\Users\\zhanx0o\\Documents\\sources\\PyflowVis\\CppProjects\\data\\DebugRobust\\X16_Y16_T5_no_mixture'
    transform: 'ToTensor'

wandb: True 

training: 
  device: 'cuda'
  # device: 'cpu'
  epochs: 200
  batch_size: 360
  shuffle: True
  num_workers: 0
  pin_memory: True


  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.000001
  # loss_function: MSELoss


  validateion_frequency: 2
  print_frequency: 100


  save_model_frequency: 100
  save_model: True
  save_model_path: 'models/'
  
