
network:
  family_name: 'CNN'
  hidden_size: 64
  dropout: 0.5
  output_size: 1
  activation: 'relu'
  

dataset:
    name: 'vastis'
    root: 'C:\\Users\\zhanx0o\\Documents\\sources\\PyflowVis\\CppProjects\\data\\Steady\\X16_Y16_Steady'
    transform: 'ToTensor'

wandb: True 

training: 
  device: 'cuda'
  # device: 'cpu'
  epochs: 300
  batch_size: 2000
  shuffle: True
  num_workers: 0
  pin_memory: True


  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.000001
  # loss_function: MSELoss


  validation_freq: 4
  print_frequency: 100


  save_model_frequency: 100
  save_model: True
  save_model_path: 'models/'
  
