
network:
  family_name: 'CNN'
  input_size: 784
  hidden_layers: [128, 64]
  output_size: 10
  activation: 'relu'
  

dataset:
    name: 'data_gen_Jun13'
    root: 'C:\\Users\\zhanx0o\\Documents\\sources\\PyflowVis\\CppProjects\\data'
    transform: 'ToTensor'

wandb: False

training: 
  device: 'cuda'
  # device: 'cpu'
  epochs: 0
  batch_size: 64
  shuffle: True
  num_workers: 0
  pin_memory: False


  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.00001
  # loss_function: MSELoss


  
  print_frequency: 100


  save_model_frequency: 10
  save_model: True
  save_model_path: 'models/'
  
