
rendering:
  restore: False
  window_size: [1600, 1200]

network:
  input_size: 784
  hidden_layers: [128, 64]
  output_size: 10
  activation: 'relu'
  

dataset:
    # datasetname: 'mnist'has this area if there are multiple datasets to select from
    root: 'C:\\Users\\zhanx0o\\Documents\\sources\\PyflowVis\\CppProjects\\data'
    time_steps: 16
    transform: 'ToTensor'

wandb: True 

training: 
  device: 'cuda'
  # device: 'cpu'
  epochs: 100
  batch_size: 48
  shuffle: True
  num_workers: 0
  pin_memory: False


  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.0001
  # loss_function: MSELoss


  
  print_frequency: 100


  save_model_frequency: 10
  save_model: True
  save_model_path: 'models/'
  
